[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "./erpc"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "erpc"
protocol = "TCP"
port = 4000
targetPort = 4000

[[services]]
name = "metrics"
protocol = "TCP"
port = 4001
targetPort = 4001